### ISSUE TITLE
TestVl3 is not stable on GKE

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/integration-k8s-gke#327]
Build: https://github.com/networkservicemesh/integration-k8s-gke/actions/runs/2054555391/attempts/1

**Comment by glazychev-art** [comment]
## Description

We know that GKE uses `af-packet` instead of `tap` (veth-pair) for a local kernel interfaces. And we have a special chain element [ipneighbors](https://github.com/networkservicemesh/sdk-kernel/tree/main/pkg/kernel/networkservice/connectioncontextkernel/ipcontext/ipneighbors) for this mechanism to add neighbor entry on the NSC side. 
This is works fine in case of a simple `point2point` example:
1. NSC send Request
2. Forwarder adds a neighbor on the backward 

_The added MAC-address is the interface address on the forwarder_

### VL3 - case
Let's take a look at the **vl3** case.
**Control-plane** ([origin](https://app.diagrams.net/#G1ryTfUl7zygIWkIj0IPpvcxiDIyjyzGeH)):

![gke_vl3-cp](https://user-images.githubusercontent.com/17748275/171840776-3cc5fd0a-a329-4058-8813-2cd69afcbcb6.svg)
1. NSCs send Requests
2. Forwarder adds a neighbor on the backward to each NSC
After that each client can ping the NSE (169.254.0.0).

But what if we want to ping NSC1 (169.254.0.1) ---> NSC2 (169.254.0.2)?
**Data plane** ([origin](https://app.diagrams.net/#G1ryTfUl7zygIWkIj0IPpvcxiDIyjyzGeH)):

![gke_vl3-dp](https://user-images.githubusercontent.com/17748275/171841693-69270874-bab6-4695-96ed-55c564933d92.svg)

NSC1 **cannot** ping NSC2 because NSC1 has not requested NSC2 and the forwarder has not configured any neighbors.

**Comment by glazychev-art** [comment]
Fixed by https://github.com/networkservicemesh/sdk/pull/1309
